### ISSUE TITLE
[doc] detailed docs for users pls

### ISSUE THREAD

**Issue by mooc9988** [huaweicloud/packer-plugin-huaweicloud#102]
Hi, I'm looking for a detailed documentation for users, but I can't seem to find it in [Packer Integrations](https://developer.hashicorp.com/packer/integrations). Additionally, I couldn't locate it in the 'docs' module within this repository. The only document available appears to be an installation guide.

**Comment by ShiChangkuo** [comment]
@mooc9988 please refer to https://github.com/huaweicloud/packer-plugin-huaweicloud/wiki get more details. I will add the link in docs and README.
