### ISSUE TITLE
Seems not supporting EU region

### ISSUE THREAD

**Issue by xianlin** [huaweicloud/packer-plugin-huaweicloud#110]
Hi, I have tried it on EU huawei cloud and here are the errors:

> Build 'huaweicloud-ecs.basic-example' errored after 1 millisecond 121 microseconds: Error initializing compute client: Discovered 2 matching endpoints: []tokens.Endpoint{tokens.Endpoint{ID:"fc26aad848c74a39b0158594f7622af3", Region:"eu-west-101", Interface:"public", URL:"[https://ces.eu-west-101.myhuaweicloud.eu/V1.0/b2c8296113c44e9492a0fd62c57f87a4"},](https://ces.eu-west-101.myhuaweicloud.eu/V1.0/b2c8296113c44e9492a0fd62c57f87a4%22%7D,) tokens.Endpoint{ID:"746d2084ae6944d5afe1a37645cd9f72", Region:"eu-west-101", Interface:"public", URL:"[https://ecs.eu-west-101.myhuaweicloud.eu/v2/b2c8296113c44e9492a0fd62c57f87a4"}}](https://ecs.eu-west-101.myhuaweicloud.eu/v2/b2c8296113c44e9492a0fd62c57f87a4%22%7D%7D)

my code is:

```
packer {
  required_version = ">= 1.2.0"
  required_plugins {
    huaweicloud = {
      version = ">= 0.4.0"
      source  = "github.com/huaweicloud/huaweicloud"
    }
  }
}

source "huaweicloud-ecs" "basic-example" {
  region             = var.region
  project_id = "ABCDEFG"
  auth_url = "https://iam.eu-west-101.myhuaweicloud.eu/v3"
  access_key         = var.access_key
  secret_key         = var.secret_key
  // enterprise_project_id = var.enterprise_project_id
  // associate_public_ip_address = false
  vpc_id                = var.vpc_id
  subnets = var.subnets
  security_groups    = ["default"]

 .... omitting some code .....

  source_image_name = "Ubuntu 22.04 server 64bit"
  // source_image_filter = {
  //   filters = {
  //     name     = "Ubuntu 20.04 server 64bit"
  //     visibility = "public"
  //   }
  //   most_recent = true
  // }
 
 ```
 
 Also I noticed the below 2 arguments are not working:
 
 ```
 // enterprise_project_id = var.enterprise_project_id
 // associate_public_ip_address = false
```

```
Error: Unsupported argument

  on /agent/_work/1/s/builds/windows/win2k22/windows-server.pkr.hcl line 15:
  (source code not available)

An argument named "enterprise_project_id" is not expected here.

Error: Unsupported argument

  on /agent/_work/1/s/builds/windows/win2k22/windows-server.pkr.hcl line 34:
  (source code not available)

An argument named "source_image_filter" is not expected here. Did you mean to
define a block of type "source_image_filter"?
```

"source_image_filter" seems not working either. could anyone give some advises? Thanks.

**Comment by xianlin** [comment]
Well, I tried with Beijing 4 region and it works, only not for EU region. Something is wrong here.

**Comment by xianlin** [comment]
now it seems working after Huawei made some changes on the backend API/SDKs.

**Comment by Zippo-Wang** [comment]
The problem has been solved by work order. Thank you for your support and recognition of our work😀
