### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by letnab** [huaweicloud/packer-plugin-huaweicloud#42]
packer version 1.6.6
plugin version 0.2.2

when I run the build I get an error

`Build 'huaweicloud-ecs.ubuntu_20_04' errored after 1 millisecond 366 microseconds: Error initializing compute client: Discovered 2 matching endpoints: []tokens.Endpoint{tokens.Endpoint{ID:"id", Region:"region", Interface:"public", URL:"https://url"}, tokens.Endpoint{ID:"id", Region:"region", Interface:"public", URL:"https://url}}`

**Comment by ShiChangkuo** [comment]
@letnab please try the latest version
