### ISSUE TITLE
packer-builder-huaweicloud-ecs source code is not in packer repository

### ISSUE THREAD

**Issue by thiagoeh** [huaweicloud/packer-plugin-huaweicloud#6]
Merging this plugin with Packer codebase would allow it to be distributed as part of the Packer binary releases.
This already happens with most builder plugins, with *packer-builder-huaweicloud-ecs* being an exception.

Here an example of a pull request, containing code for another builder plugin (from a much smaller cloud provider, by the way):
https://github.com/hashicorp/packer/pull/7508

**Comment by ShiChangkuo** [comment]
Hi @thiagoeh 

The latest release v0.4.0 can support packer 1.7.0+ and `packer init` command, please try it.
Also, you can get the documentation from https://www.packer.io/docs/builders/huaweicloud
