### ISSUE TITLE
support spot marketType

### ISSUE THREAD

**Issue by ysicing** [huaweicloud/packer-plugin-huaweicloud#79]

**Comment by ShiChangkuo** [comment]
@ysicing do you mean that add an spot option for the temporary VM?

**Comment by ysicing** [comment]
yes, add spot option  for frequent builds to save some money

**Comment by ShiChangkuo** [comment]
Good idea! we will implement this feature before June 30th.

**Comment by ysicing** [comment]
Ok, I looked at the code implementation and it seems to be more complex than Tencent Cloud and different from the official Open API best practices
