### ISSUE TITLE
Adding support for ecs resource system disk

### ISSUE THREAD

**Issue by rhtot** [huaweicloud/packer-plugin-huaweicloud#80]
Hi there, 

As per the documentation https://support.huaweicloud.com/intl/en-us/bestpractice-ims/ims_bp_0031.html claims, there is a possibility to edit the temporary ecs resource flavor 
![image](https://user-images.githubusercontent.com/91057976/224680124-9329c142-58a6-4c8d-9368-7668352a2e7c.png)
, but I see no possibility to do so in the case of the os disk size and type.

Is this something that is already implemented but not yet documented, or the feature is missing?

If the latter one is true, could you please implement it?

Thank you for your feedback in advance,
Robert

**Comment by rhtot** [comment]
Update:
In the meantime, it seems using `volume_size` parameter does the trick for the size.

**Comment by ShiChangkuo** [comment]
@rhtot please refer https://github.com/huaweicloud/packer-plugin-huaweicloud/wiki to get the parameters of huaweicloud plugin
